/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jimage;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.image.BufferedImage;
import org.jfree.chart.*;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYSplineRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;



/**
 *
 * @author yeray
 */
public class JInternalFrame1 extends javax.swing.JInternalFrame {

    JLabel JLabel_imagen;
    BufferedImage imagen;
    /**
     * Creates new form JInternalFrame1
     */
public JInternalFrame1() {
        initComponents();
                   
    }

public JInternalFrame1(BufferedImage img) {
        initComponents();
        imagen= img;
    
}

public void abrir_imagen (BufferedImage img){
    String title = "ImagenSinTitulo";
    JLabel_imagen= new JLabel();
    this.add(JLabel_imagen);
    
    
    if (img == null){
        abrir_imagen a = new abrir_imagen();
        imagen= a.LeerImagen();
        title = a.path.substring(a.path.lastIndexOf("/")+1);
    }
    else imagen = img;
    
    if (imagen != null) 
    {
        setJInternalImageFrame(title, imagen.getWidth(),imagen.getHeight());
        //Cargamos el JLabel con la imagen como ImageIcon
        
        JLabel_set_imagen();
    }
    else {
 
    }
    

}
    public void setJInternalImageFrame(String title, int width, int height){

        this.setMaximizable(true);
        this.setClosable(true);
        this.setIconifiable(true);

        this.setTitle(title);
        this.setVisible(true);
        this.setSize(width, height);
      
        
       
   

}
        
    public void JLabel_set_imagen(){
        
        ImageIcon icono =new ImageIcon(imagen);
        JLabel_imagen.setIcon(icono);
        this.JLabel_imagen.setBounds(0, 0, imagen.getWidth(), imagen.getHeight());
    }
    
    public void pasar_a_bw(){
        pixel_imagen tmp = new pixel_imagen();
        tmp.img_to_BW(imagen);
        JLabel_set_imagen();   
    }

    public void ver_histograma_abs(){
    
        ChartPanel panel;
        JFreeChart chart;
        XYSplineRenderer renderer = new XYSplineRenderer();;
        XYSeriesCollection dataset = new XYSeriesCollection();
        
        ValueAxis x = new NumberAxis();
        ValueAxis y = new NumberAxis();
        
        XYSeries serie = new XYSeries("Datos");
        XYPlot plot;
        
        pixel_imagen tmp = new pixel_imagen();
        int[] hist = tmp.img_get_histogramaAbs(imagen);
        
        for(int fila=0;fila<255;fila++){
            serie.add(fila, hist[fila]);   
        }
        
        dataset.addSeries(serie);
        //x.setLabel("Color");
        //y.setLabel("Veces");
        chart = ChartFactory.createHistogram("Histograma Absoluto", title, title, dataset, PlotOrientation.VERTICAL, isClosed, closable, isClosed);
             
        plot = new XYPlot(dataset,x,y,renderer);
        plot.isDomainCrosshairVisible();
        plot.isRangeCrosshairVisible();
        plot.isRangeGridlinesVisible();
        
        
        //chart = new JFreeChart(plot);
        //chart.setTitle("Histograma Absoluto");
        
        panel = new ChartPanel(chart);
        panel.setBounds(5,10,400,400);
        
        setJInternalImageFrame("Diagrama Absoluto", 450,450);
        this.add(panel);
        this.repaint();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
