/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jimage;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author yeray
 */
public class JInternalOption extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalOption
     */
    pixel_imagen tmp;
    BufferedImage original_image;
    BufferedImage dest_image;
    JInternalFrame1 jif1;

    public JInternalOption(JInternalFrame1 jif) {
        jif1= jif;
        BufferedImage imagen = jif.imagen;
        initComponents();
        dest_image = imagen;
       
        BufferedImage img = new BufferedImage(imagen.getWidth(),imagen.getHeight(),BufferedImage.TYPE_INT_RGB);
        //Creo una copia de BufferedImage
        Graphics g = img.createGraphics();
        g.drawImage(imagen, 0, 0, null);
        g.dispose();
        original_image = img;
        
         tmp = new pixel_imagen();
         
          pixel_imagen a = new pixel_imagen();
         jSlider1.setValue((int)a.getBrillo(original_image));
         jSlider2.setValue((int)a.getContraste(original_image));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Brillo / Contraste");

        jSlider1.setMaximum(255);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setToolTipText("ds");
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel1.setText("Brillo");

        jSlider2.setMaximum(127);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setSnapToTicks(true);
        jSlider2.setValue(0);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        jLabel2.setText("Contraste");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        //BRILLO
        //double mapedbr;
        //mapedbr = (jSlider1.getValue()-50)*(5.1);
        //double mapedcr;
        //mapedcr = (jSlider2.getValue()-50)*(5.1);
       
        //int value = a.getBrillo(original_image);
        
        jLabel1.setText("Brillo "+ jSlider1.getValue());
        tmp.brilloContraste(original_image, dest_image, jSlider1.getValue(), jSlider2.getValue());
        jif1.repaint();
        
        
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        //CONTRASTE
        double maped;
        maped = (jSlider2.getValue()-50)*(5.1);
         jLabel2.setText("Contraste "+ jSlider2.getValue());
       // tmp.contraste(original_image, dest_image, maped);
        tmp.brilloContraste(original_image, dest_image, jSlider1.getValue(), jSlider2.getValue());
        
         jif1.repaint();
    }//GEN-LAST:event_jSlider2StateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    // End of variables declaration//GEN-END:variables
}
