/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jimage;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.image.BufferedImage;


/**
 *
 * @author yeray
 */
public class JInternalFrame1 extends javax.swing.JInternalFrame {

    JLabel JLabel_imagen;
    BufferedImage imagen;
    /**
     * Creates new form JInternalFrame1
     */
public JInternalFrame1() {
        initComponents();
                   
    }

public void abrir_imagen (BufferedImage img){
    String title = "ImagenSinTitulo";
    JLabel_imagen= new JLabel();
    this.add(JLabel_imagen);
    
    if (img == null){
        abrir_imagen a = new abrir_imagen();
        imagen= a.LeerImagen();
        title = a.path.substring(a.path.lastIndexOf("/")+1);
    }
    else imagen = img;
    
    if (imagen != null) 
    {
        setJInternalImageFrame(title, imagen.getHeight(),imagen.getWidth());
        //Cargamos el JLabel con la imagen como ImageIcon
        JLabel_set_imagen();
    }
    else {
 
    }
    

}
    public void setJInternalImageFrame(String title, int height, int width){

        this.setMaximizable(true);
        this.setClosable(true);
        this.setIconifiable(true);

        this.setTitle(title);
        this.setVisible(true);
        this.setSize(height,width);
        
        this.JLabel_imagen.setBounds(0, 0, height, width);
   

}
        
    public void JLabel_set_imagen(){
        
        ImageIcon icono =new ImageIcon(imagen);
        JLabel_imagen.setIcon(icono);
    }
    
    public void pasar_a_bw(){
        pixel_imagen tmp = new pixel_imagen();
        tmp.toBW(imagen);
        JLabel_set_imagen();   
    }

    public void ver_histograma_abs(){
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
